# Generated by Django 4.1.7 on 2023-02-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_img', models.URLField()),
                ('thumbnail_img', models.URLField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='venues.venuecontact')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='users.venueowner')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='venues.venue')),
            ],
        ),
    ]
