# Generated by Django 4.1.7 on 2023-03-01 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuecontact',
            name='venue_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='venues.Venue'),
            preserve_default=False,
        ),
    ]
