# Generated by Django 4.1.7 on 2023-03-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        ('events', '0004_rename_seat_type_id_eventseattype_venue_seat_type_id_and_more'),
        ('venues', '0004_remove_venuecontact_venue_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeatType',
            new_name='VenueSeatType',
        ),
    ]
