# Generated by Django 4.1.7 on 2023-03-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venuecontact_venue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuecontact',
            name='venue_id',
        ),
    ]
