# Generated by Django 4.1.7 on 2023-03-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_remove_venuecontact_venue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuecontact',
            name='venue_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='venues.venue'),
            preserve_default=False,
        ),
    ]
