# Generated by Django 4.1.7 on 2023-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venuecontact_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='cover_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
