# Generated by Django 4.1.7 on 2023-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_alter_venue_cover_img_alter_venue_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='venuecontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
