# Generated by Django 4.1.7 on 2023-03-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_alter_venuecontact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='venues.venuecontact'),
        ),
    ]
