# Generated by Django 4.1.7 on 2023-03-04 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0012_alter_venue_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
