# Generated by Django 4.1.7 on 2023-03-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_alter_venue_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
