# Generated by Django 4.1.7 on 2023-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_venue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
