# Generated by Django 4.1.7 on 2023-03-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_alter_venuecontact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueseattype',
            name='price',
        ),
    ]
