# Generated by Django 4.1.7 on 2023-03-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_remove_venueseattype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueseattype',
            name='total_seats',
            field=models.IntegerField(default=1),
        ),
    ]
