# Generated by Django 4.1.7 on 2023-03-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_alter_venueseattype_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueseattype',
            name='description',
        ),
        migrations.AlterField(
            model_name='venueseattype',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
