# Generated by Django 4.1.7 on 2023-02-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseattype',
            name='seat_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.seattype'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venues.venue'),
        ),
    ]
