# Generated by Django 4.1.7 on 2023-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('THEATER', 'Theater'), ('SPORTS', 'Sports'), ('OTHERS', 'Others')], default='OTHERS', max_length=30),
        ),
    ]
