# Generated by Django 4.1.7 on 2023-03-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_venuecontact_venue_id'),
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventseattype',
            old_name='seat_type_id',
            new_name='venue_seat_type_id',
        ),
        migrations.AlterUniqueTogether(
            name='eventseattype',
            unique_together={('event_id', 'venue_seat_type_id')},
        ),
    ]
