# Generated by Django 4.1.7 on 2023-03-05 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_seat_type_id_eventseattype_venue_seat_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseattype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='eventseattype',
            name='available_seats',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
