# Generated by Django 4.1.7 on 2023-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventseattype_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_img',
            field=models.URLField(blank=True),
        ),
    ]
