# Generated by Django 4.1.7 on 2023-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_remove_venueseattype_description_and_more'),
        ('events', '0006_event_cover_img_event_thumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date', 'time', 'venue_id')},
        ),
    ]
