# Generated by Django 4.1.7 on 2023-03-06 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventseattype_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseattype',
            name='available_seats',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
