# Generated by Django 4.1.7 on 2023-03-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventseattype_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventseattype',
            managers=[
            ],
        ),
    ]
