# Generated by Django 4.1.7 on 2023-03-07 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventseattype_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseattype',
            name='available_seats',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
