# Generated by Django 4.1.7 on 2023-03-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventseattype_managers'),
        ('tickets', '0003_remove_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.eventseattype'),
        ),
    ]
