# Generated by Django 4.1.7 on 2023-03-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_remove_venueseattype_description_and_more'),
        ('tickets', '0005_alter_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='venues.venueseattype'),
        ),
    ]
